version: '3.8'

networks:
  default:
    external:
      name: jenkins-net

services:

  dind:
    image: docker:dind
    container_name: dind
    restart: always
    privileged: true
    command: ['--insecure-registry=127.0.0.1:8000']
    networks:
      default:
        aliases:
          - docker
    ports:
      - '2376:2376'
    volumes:
      - './jenkins_home:/var/jenkins_home'
      - './jenkins_docker_certs:/certs/client'
    environment:
      DOCKER_TLS_CERTDIR: '/certs'

  jenkins:
    image: jenkins/jenkins:2.263.4-lts-jdk11
    container_name: jenkins
    restart: always
    depends_on:
      - dind
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - './jenkins_home:/var/jenkins_home'
      - './jenkins_docker_certs:/certs/client:ro'
      - '/usr/bin/docker:/usr/bin/docker'
    environment:
      DOCKER_HOST: 'tcp://docker:2376'
      DOCKER_CERT_PATH: '/certs/client'
      DOCKER_TLS_VERIFY: 1
      JAVA_OPTS: '-Xmx1024m -Djava.awt.headless=true'
      TZ: 'Asia/Seoul'
